name: animeganv2
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=1.10
  - cudatoolkit=11.3
  - pycodestyle
  - numpy
  - pandas
  - conda-forge::opencv
  - pip
  - pip:
    - black
    - pytorch-lightning==1.5
    - torchmetrics
    - torchvision
    - ruyaml
    - icecream
    - rich